title: "Rachid Abou Djamal Hamadou — Portfolio"
description: "Data Science & AI student portfolio."

baseurl: ""
url: "https://tole-corne.github.io"

markdown: kramdown
theme: null

author: "Rachid Abou Djamal Hamadou"
github_username: "tole-corne"

exclude:
  - "README.md"
